export const CREATE_BOOK = 'CREATE_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';

export const ADD_TO_LIBRARY = 'ADD_TO_LIBRARY';
export const REMOVE_FROM_LIBRARY = 'REMOVE_FROM_LIBRARY';

export const SHOW_ADD_TO_LIBRARY_MODAL = 'SHOW_ADD_TO_LIBRARY_MODAL';
export const HIDE_ADD_TO_LIBRARY_MODAL = 'HiDE_ADD_TO_LIBRARY_MODAL';

export const SHOW_CREATE_BOOK_MODAL = 'SHOW_CREATE_BOOK_MODAL';
export const HIDE_CREATE_BOOK_MODAL = 'HIDE_CREATE_BOOK_MODAL';

export const SHOW_DELETE_BOOK_MODAL = 'SHOW_DELETE_BOOK_MODAL';
export const HIDE_DELETE_BOOK_MODAL = 'HIDE_DELETE_BOOK_MODAL';
